src/objects/Bed_Night__c.object
<CustomObject>
    <fields>
        <fullName>Bednight_Date__c</fullName>
        <label>Bednight Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Bednight_Notes__c</fullName>
        <description>If a someone leaves/returns during their stay and we cannot count the bednight, enter brief reason here.</description>
        <inlineHelpText>If a someone leaves/returns during their stay and we cannot count the bednight, enter brief reason here.</inlineHelpText>
        <label>Bednight Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Case_Record__c</fullName>
        <description>Parent Case Record</description>
        <inlineHelpText>Parent Case Record</inlineHelpText>
        <label>Case Record</label>
        <referenceTo>Case_Record__c</referenceTo>
        <relationshipLabel>Bed Nights</relationshipLabel>
        <relationshipName>Bed_Nights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Present__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Was the participant present at the shelter?</description>
        <inlineHelpText>Was the participant present at the shelter?</inlineHelpText>
        <label>Present</label>
        <type>Checkbox</type>
    </fields>
    <label>Bed Night</label>
    <nameField>
        <displayFormat>BD-{00000}</displayFormat>
        <label>Bed Night Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bed Nights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Record__c.object
<CustomObject>
    <label>Case Record</label>
    <nameField>
        <label>Case Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EditBedNightsControllerExtension.cls
/** 
* Written by N Martinov , copyright (c) 2015 501Commons
* Controller extension for page used to inline edit bed nights
*/
public without sharing class EditBedNightsControllerExtension {
    private Id crId; 
    private Case_Record__c cr;
    private List<Bed_Night__c> bedNights{get; private set;}   
    private boolean saveComplete = false;
    public static Integer PAGE_SIZE = 15;
        
    public EditBedNightsControllerExtension (ApexPages.StandardSetController stdController) {
      crId= ApexPages.currentPage().getParameters().get('id');
      cr = [select name from Case_Record__c where id=:crId];
    }
    
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [SELECT id, Name, Bednight_Date__c, Bednight_Notes__c, Present__c 
                            FROM Bed_Night__c 
                            where Case_Record__c=:crId order by Bednight_Date__c desc limit 200]));
                setCon.setPageSize(PAGE_SIZE);          
            }
            return setCon;
        }
        set;
    }

    // Initialize setCon and return a list of records
    public List<Bed_Night__c> getBedNights() {
        return (List<Bed_Night__c>) setCon.getRecords();
    }
    
    public Case_Record__c getCaseRecord() {
        return cr;
    }
    
    public String getCaseRecordName() {
        return cr.Name;
    }
     
    public void save() {
        Integer pageNumber = setCon.getPageNumber();
        update setCon.getRecords();     
        //clear previous and next
        setCon.reset();     
        if(pageNumber!= 1) {
            setCon.setPageNumber(pageNumber - 1);
            setCon.next();
        }       
        saveComplete = true;    
    }    
    
    public Boolean getSaveComplete() {
        return saveComplete;
    }
    
    public Boolean hasNext {
        get {
            return setCon.getHasNext();
        }
        set;
    }
    public Boolean hasPrevious {
        get {
            return setCon.getHasPrevious();
        }
        set;
    }     
  
    public void previous() {
        saveComplete = false;
        setCon.previous();
    }
  
    public void next() {
        saveComplete = false;
        setCon.next();
    }
    
    public PageReference clearMsg() {       
        saveComplete = false;
        return null;        
    }
           
}