src/objects/Bed_Night__c.object
<CustomObject>
    <fields>
        <fullName>Bednight_Date__c</fullName>
        <label>Bednight Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Bednight_Notes__c</fullName>
        <description>If a someone leaves/returns during their stay and we cannot count the bednight, enter brief reason here.</description>
        <inlineHelpText>If a someone leaves/returns during their stay and we cannot count the bednight, enter brief reason here.</inlineHelpText>
        <label>Bednight Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Case_Record__c</fullName>
        <description>Parent Case Record</description>
        <inlineHelpText>Parent Case Record</inlineHelpText>
        <label>Case Record</label>
        <referenceTo>Case_Record__c</referenceTo>
        <relationshipLabel>Bed Nights</relationshipLabel>
        <relationshipName>Bed_Nights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Present__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Was the participant present at the shelter?</description>
        <inlineHelpText>Was the participant present at the shelter?</inlineHelpText>
        <label>Present</label>
        <type>Checkbox</type>
    </fields>
    <label>Bed Night</label>
    <nameField>
        <displayFormat>BD-{00000}</displayFormat>
        <label>Bed Night Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bed Nights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Record__c.object
<CustomObject>
    <label>Case Record</label>
    <nameField>
        <label>Case Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestEditBedNightsControllerExtension.cls
@isTest
private class TestEditBedNightsControllerExtension{

    @isTest
    static void testController() {
        TestHarness th = new TestHarness();        
        th.createEnrollment();
        //create some bednights
        List<Bed_Night__c> bnights = new List<Bed_Night__c>();
        for (Integer i=0; i<10; i++) {
            Bed_Night__c b = new Bed_Night__c(Case_Record__c=th.cr.id, Bednight_Date__c=date.today()-i);
            bnights.add(b);
        }        
        insert bnights;
        test.startTest();        
        
        ApexPages.StandardSetController stdContr = new ApexPages.StandardSetController(new List<Bed_Night__c>()); 
        ApexPages.currentPage().getParameters().put('id', th.cr.Id);
        EditBedNightsControllerExtension contrExt = new EditBedNightsControllerExtension(stdContr);
        
        List<Bed_Night__c> bedNightsFromController = contrExt.getBedNights();
        System.assertEquals(10, bedNightsFromController.size()); 
        for (Bed_Night__c b : bedNightsFromController) {
            System.assertEquals(null, b.Bednight_Notes__c);
            b.Present__c = true;
        }
        contrExt.save();
        System.assert(contrExt.getSaveComplete());
        bedNightsFromController = contrExt.getBedNights();
        for (Bed_Night__c b : bedNightsFromController ) {
            System.assert(b.Present__c);            
        }
        System.assertEquals(th.cr.Name, contrExt.getCaseRecordName());
        System.assertEquals(th.cr.Id, contrExt.getCaseRecord().Id);
        
        System.assert(!contrExt.hasNext);
        System.assert(!contrExt.hasPrevious);
                        
        contrExt.previous();
        System.assertEquals(10, contrExt.getBedNights().size());
        
        contrExt.next();
        System.assertEquals(10, contrExt.getBedNights().size());
        System.assertEquals(null, contrExt.clearMsg());
    }
    
    
}