src/objects/Case_Record__c.object
<CustomObject>
    <label>Case Record</label>
    <nameField>
        <label>Case Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceParticipation__c.object
<CustomObject>
    <description>Models the participation of a client in a service.</description>
    <fields>
        <fullName>Case_Record__c</fullName>
        <description>The Case Record under which this Client participated or was provided the Service.</description>
        <inlineHelpText>The Case Record under which this Client participated or was provided the Service.</inlineHelpText>
        <label>Case Record</label>
        <referenceTo>Case_Record__c</referenceTo>
        <relationshipLabel>Service Participations</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Goals__c</fullName>
        <label>Goals</label>
        <picklist>
            <controllingField>Goals_Week__c</controllingField>
            <picklistValues>
                <fullName>1 Docs: Obtain important: (Pic ID, etc.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Docs: Req funding for important docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Docs:  Important docs obtained?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0 DV Ed: Review last week. Thoughts?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 DV Education: Week 1 (DV 101)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 DV Ed: Week 2 / Topic entered in notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 DV Ed: Week 3 / Topic entered in notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 DV Ed: Week 4 / Topic entered in notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 DV Ed: Week 5 / Topic entered in notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 DV Ed: Week 6 / Topic entered in notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 DV Ed: Week 7 / Topic entered in notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0 Finance:  SS Plan - Edu, Job, SSDI,etc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Finance:  DSHS (Food Stamps, TANF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Finance:  DSHS (Med Coupons)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Finance: Resume / Job search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Finance: Actively seeking employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Finance: Barriers to Self-Suffncy Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Health: Basic Health/MH resource needs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Housing: Complete Housing Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Housing: Families - Discuss alt to FHC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Housing: Fam - Obtain FHC ROI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Housing: Fam - Sign up for FHC assesmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Housing: Fam- Update FHC Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Housing: Go over THP guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Housing: Fam -  FHC appt.(Date &amp; loc?)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Housing: Go over unfinished apps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Housing: Tips/Barriers/Ways to address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Housing: Search /Open apps./ New Oppty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Housing:  Self-Advocacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Legal: Explain Legal Resources/Options</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Service Participation</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Service Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestServiceParticipationGoalsTrigger.cls
@isTest
private class TestServiceParticipationGoalsTrigger {
    static testMethod void updateServiceParticipation(){
        // get the case record for Marge Simpson
        Case_Record__c c = [SELECT Id, Name, (SELECT Id from Participations__r) from Case_Record__c WHERE Name like '%SH PART-01888 11/2014 Case Record%'];
        system.debug('test:' + c);
        // retrieve the first ServiceParticipation__c
        /*
        ServiceParticipation__c sp = c.Participations__r.get(0); 
        system.debug('[rpop] sp:' + sp.Goals__c);
		*/
    }
}